var season = [
    {
        id: 1,
        img: "../images/sub/menu/20211231115534_Strawberry Juice.png",
        name: "스트로베리 주스",
        status: "Ice",
        info: {
            eng: "Strawberry Juice",
            expl: "새콤달콤한 제철 생딸기가 듬뿍 더해져 상큼달콤하게 즐길 수 있는 주스",
            nut: "나트륨 4mg, 당류 2g, 포화지방 0g, 단백질 1g, 카페인 0mg ",
            orig: "",
            alg: "",
        },
    },
    {
        id: 2,
        img: "../images/sub/menu/20211231115620_Strawberry Latte.png",
        name: "스트로베리 라떼",
        status: "Ice",
        info: {
            eng: "Strawberry Latte",
            expl: "시즌 한정으로, 생딸기가 더해져 더욱 더 달콤하고 진하게 즐길 수 있는 라떼",
            nut: "나트륨 66mg, 당류 13g, 포화지방 3g, 단백질 6g, 카페인 0mg",
            orig: "",
            alg: "우유",
        },
    },
    {
        id: 3,
        img: "../images/sub/menu/20211231115722_Strawberry Spanner.png",
        name: "스트로베리슈페너",
        status: "Ice",
        info: {
            eng: "Strawberry Spanner",
            expl: "시즌 한정으로, 부드러운 딸기크림과 달콤한 딸기 라떼를 함께 즐길 수 있는 베리슈페너",
            nut: "나트륨 70mg, 당류 15g, 포화지방 10g, 단백질 6g, 카페인 0mg ",
            orig: "",
            alg: "우유",
        },
    },
    {
        id: 4,
        img: "../images/sub/menu/20211231115818_Double Berry Blacktea-I.png",
        name: "더블베리 블랙티",
        status: "Both",
        info: {
            eng: "Double Berry Blacktea",
            expl: "향긋한 얼그레이티와 상큼달콤한 생딸기, 블루베리가 어우러진 블렌딩티",
            nut: "나트륨 13mg, 당류 14g, 포화지방 0g, 단백질 1g, 카페인 39mg",
            orig: "",
            alg: "",
        },
    },
    {
        id: 5,
        img: "../images/sub/menu/20211231115919_Strawberry Yoghurt Ice Blended.png",
        name: "스트로베리 요거트",
        status: "Ice",
        info: {
            eng: "Strawberry Yoghurt Ice Blended",
            expl: "상큼한 요거트에 딸기를 듬뿍 더해 보다 더 진하고 풍성하게 즐길 수 있는 블렌디드",
            nut: "나트륨 57mg, 당류 37g, 포화지방 2g, 단백질 4g, 카페인 0mg",
            orig: "",
            alg: "우유",
        },
    },
    {
        id: 6,
        img: "../images/sub/menu/20211231120011_Strawberry Croud Ice Blended.png",
        name: "스트로베리 클라우드",
        status: "Ice",
        info: {
            eng: "Strawberry Cloud Ice Blended",
            expl: "상큼한 딸기블렌디드에 구름을 연상시키는 부드러운 크림을 더한 비주얼로 눈과 입으로 즐기는 블렌디드",
            nut: "나트륨 61mg, 당류 20g, 포화지방 6g, 단백질 2g, 카페인 0mg ",
            orig: "",
            alg: "우유",
        },
    },
    {
        id: 7,
        img: "../images/sub/menu/20211231120327_Double Berry Greek Yoghurt.png",
        name: "더블베리 요거트볼",
        status: "",
        info: {
            eng: "Double Berry Greek Yoghurt",
            expl: "상큼달콤한 생딸기와 블루베리를 그릭요거트와 함께 즐길 수 있는 요거트볼",
            nut: "나트륨 55mg, 당류 10g, 포화지방 2g, 단백질 6g, 카페인 0mg ",
            orig: "",
            alg: "우유",
        },
    },
    {
        id: 8,
        img: "../images/sub/menu/20220119182425_Tiramisu-Cube.png",
        name: "스트로베리 큐브",
        status: "",
        info: {
            eng: "Strawberry Cube",
            expl: "부드럽고 고소한 끼리 크림치즈와 딸기쥬레로 맛을 더한 티라미수에 제철 생딸기를 듬뿍 올린 딸기 티라미수",
            nut: "나트륨 198mg, 당류 18g, 포화지방 19g, 단백질 5g",
            orig: "딸기(국내산), 가공유크림(덴마크), 끼리크림치즈(프랑스), 과채가공품{딸기(칠레산),설탕} ",
            alg: "알류, 우유, 대두, 밀, 돼지고기, 아황산류 ",
        },
    },
];
